// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: tune_bar

#include "../ui.h"

lv_obj_t *ui_Screen_Boot = NULL;lv_obj_t *ui_Boot_Image_tunebar = NULL;
// event funtions
void ui_event_Screen_Boot( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      appStart( e );
      slide_Animation(ui_Boot_Image_tunebar, 0);
}
}

// build funtions

void ui_Screen_Boot_screen_init(void)
{
ui_Screen_Boot = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_Boot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Screen_Boot, &ui_img_images_vaandcobbanner_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Boot_Image_tunebar = lv_img_create(ui_Screen_Boot);
lv_img_set_src(ui_Boot_Image_tunebar, &ui_img_images_tunebar_png);
lv_obj_set_width( ui_Boot_Image_tunebar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Boot_Image_tunebar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Boot_Image_tunebar, 642 );
lv_obj_set_y( ui_Boot_Image_tunebar, 0 );
lv_obj_set_align( ui_Boot_Image_tunebar, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Boot_Image_tunebar, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Boot_Image_tunebar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Screen_Boot, ui_event_Screen_Boot, LV_EVENT_ALL, NULL);

}

void ui_Screen_Boot_screen_destroy(void)
{
   if (ui_Screen_Boot) lv_obj_del(ui_Screen_Boot);

// NULL screen variables
ui_Screen_Boot= NULL;
ui_Boot_Image_tunebar= NULL;

}
